/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent 列表（?q=&status=&tag=） */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        /** 新建 Agent（校验引用与白名单） */
        post: operations["create_agent_api_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent 详情 */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** 软删除 Agent */
        delete: operations["delete_agent_api_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** 更新 Agent（prompt 变更留档） */
        patch: operations["update_agent_api_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 复制为新 Agent */
        post: operations["clone_agent_api_v1_agents__agent_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/prompt-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt 历史版本 */
        get: operations["list_prompt_versions_api_v1_agents__agent_id__prompt_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话列表（?agent_id=&q=） */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** 创建会话（{agent_id, title?}） */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话详情 */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** 删除会话 */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** 重命名 / 归档 */
        patch: operations["update_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 消息列表（游标分页，默认最近 50 条） */
        get: operations["list_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /** 一轮对话，返回 SSE 流 */
        post: operations["create_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 版本与能力开关
         * @description `features` 取启动时的快照（6.3 第 5 条）；未跑 lifespan 时（如单测直接调用）回退为即时计算。
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider 列表 */
        get: operations["list_model_providers_api_v1_model_providers_get"];
        put?: never;
        /** 新建 Provider（api_key 加密存储） */
        post: operations["create_model_provider_api_v1_model_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider 详情 */
        get: operations["get_model_provider_api_v1_model_providers__provider_id__get"];
        put?: never;
        post?: never;
        /** 删除 Provider（被引用 → 409） */
        delete: operations["delete_model_provider_api_v1_model_providers__provider_id__delete"];
        options?: never;
        head?: never;
        /** 更新 Provider */
        patch: operations["update_model_provider_api_v1_model_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/v1/model-providers/{provider_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 连通性检测（1-token） */
        post: operations["test_model_provider_api_v1_model_providers__provider_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行列表（?kind=&agent_id=&status=） */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行详情（含 steps / token / cost） */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消运行中的 Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spans/{span_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个 span（含 input/output） */
        get: operations["get_span_api_v1_spans__span_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool-invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工具调用明细（?run_id=&tool_id=）
         * @description 2.5：Trace 之外仍可 SQL 查询的审计行；最新在前。
         */
        get: operations["list_tool_invocations_api_v1_tool_invocations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工具列表（?tool_type=&status=&q=）
         * @description 3.2.3：内置在前、按名称排序；`?status=` 用 `Query(alias=...)` 暴露（同 `traces.py` 的 `from`/`to`）。
         */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工具详情（含 http_config）
         * @description 不存在 → `TOOL_NOT_FOUND`（404）。
         */
        get: operations["get_tool_api_v1_tools__tool_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace 列表（游标分页） */
        get: operations["list_traces_api_v1_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace 概要 + 扁平 span 列表 */
        get: operations["get_trace_api_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探针
         * @description 不查任何依赖（6.3）：只要进程还能响应就是 ok。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针 */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentCloneRequest
         * @description `POST /agents/{id}/clone`（3.2.2）。
         */
        AgentCloneRequest: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /**
         * AgentCreate
         * @description 3.3.1 的请求体（`tool_ids` / `knowledge_base_ids` / `workflow_id` 在 Phase 1 必须为空）。
         */
        AgentCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Template
             * @default false
             */
            is_template: boolean;
            /** Knowledge Base Ids */
            knowledge_base_ids?: string[];
            /**
             * Max Steps
             * @default 8
             */
            max_steps: number;
            memory_config?: components["schemas"]["MemoryConfigDTO"];
            /** Model Name */
            model_name: string;
            /** Model Params */
            model_params?: {
                [key: string]: unknown;
            };
            /** Model Provider Id */
            model_provider_id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @default enabled
             * @enum {string}
             */
            status: "enabled" | "disabled";
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** Tags */
            tags?: string[];
            /**
             * Timeout Seconds
             * @default 180
             */
            timeout_seconds: number;
            /** Tool Ids */
            tool_ids?: string[];
            /** Workflow Id */
            workflow_id?: string | null;
        };
        /** AgentPromptVersionRead */
        AgentPromptVersionRead: {
            /** Agent Id */
            agent_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** System Prompt */
            system_prompt: string;
            /** Version */
            version: number;
        };
        /** AgentRead */
        AgentRead: {
            /** Created At */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /**
             * Is Template
             * @default false
             */
            is_template: boolean;
            /** Knowledge Base Ids */
            knowledge_base_ids?: string[];
            /**
             * Max Steps
             * @default 8
             */
            max_steps: number;
            /** Memory Config */
            memory_config?: {
                [key: string]: unknown;
            };
            /** Model Name */
            model_name: string;
            /** Model Params */
            model_params?: {
                [key: string]: unknown;
            };
            /** Model Provider Id */
            model_provider_id: string;
            /** Name */
            name: string;
            /**
             * Prompt Version
             * @default 1
             */
            prompt_version: number;
            /**
             * Status
             * @default enabled
             */
            status: string;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** Tags */
            tags?: string[];
            /**
             * Timeout Seconds
             * @default 180
             */
            timeout_seconds: number;
            /** Tool Ids */
            tool_ids?: string[];
            /** Updated At */
            updated_at: string;
            /** Workflow Id */
            workflow_id?: string | null;
        };
        /**
         * AgentUpdate
         * @description `PATCH`：只传需要改的字段；`system_prompt` 变化会写 `agent_prompt_versions`（2.4）。
         */
        AgentUpdate: {
            /** Description */
            description?: string | null;
            /** Max Steps */
            max_steps?: number | null;
            memory_config?: components["schemas"]["MemoryConfigDTO"] | null;
            /** Model Name */
            model_name?: string | null;
            /** Model Params */
            model_params?: {
                [key: string]: unknown;
            } | null;
            /** Model Provider Id */
            model_provider_id?: string | null;
            /** Name */
            name?: string | null;
            /** Prompt Note */
            prompt_note?: string | null;
            /** Status */
            status?: ("enabled" | "disabled") | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
        };
        /** ApiResponse[AgentRead] */
        ApiResponse_AgentRead_: {
            data: components["schemas"]["AgentRead"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ConversationRead] */
        ApiResponse_ConversationRead_: {
            data: components["schemas"]["ConversationRead"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[MetaData] */
        ApiResponse_MetaData_: {
            data: components["schemas"]["MetaData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ProviderRead] */
        ApiResponse_ProviderRead_: {
            data: components["schemas"]["ProviderRead"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ProviderTestResult] */
        ApiResponse_ProviderTestResult_: {
            data: components["schemas"]["ProviderTestResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[RunRead] */
        ApiResponse_RunRead_: {
            data: components["schemas"]["RunRead"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[SpanRead] */
        ApiResponse_SpanRead_: {
            data: components["schemas"]["SpanRead"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ToolDetail] */
        ApiResponse_ToolDetail_: {
            data: components["schemas"]["ToolDetail"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[TraceDetail] */
        ApiResponse_TraceDetail_: {
            data: components["schemas"]["TraceDetail"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[AgentPromptVersionRead]] */
        ApiResponse_list_AgentPromptVersionRead__: {
            /** Data */
            data: components["schemas"]["AgentPromptVersionRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[AgentRead]] */
        ApiResponse_list_AgentRead__: {
            /** Data */
            data: components["schemas"]["AgentRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[ConversationRead]] */
        ApiResponse_list_ConversationRead__: {
            /** Data */
            data: components["schemas"]["ConversationRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[MessageRead]] */
        ApiResponse_list_MessageRead__: {
            /** Data */
            data: components["schemas"]["MessageRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[ProviderRead]] */
        ApiResponse_list_ProviderRead__: {
            /** Data */
            data: components["schemas"]["ProviderRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[RunRead]] */
        ApiResponse_list_RunRead__: {
            /** Data */
            data: components["schemas"]["RunRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[ToolInvocationRead]] */
        ApiResponse_list_ToolInvocationRead__: {
            /** Data */
            data: components["schemas"]["ToolInvocationRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[ToolRead]] */
        ApiResponse_list_ToolRead__: {
            /** Data */
            data: components["schemas"]["ToolRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[TraceRead]] */
        ApiResponse_list_TraceRead__: {
            /** Data */
            data: components["schemas"]["TraceRead"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Agent Id */
            agent_id: string;
            /** Title */
            title?: string | null;
        };
        /** ConversationRead */
        ConversationRead: {
            /** Agent Id */
            agent_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Last Message At */
            last_message_at?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Owner Key
             * @default local
             */
            owner_key: string;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Status */
            status?: ("active" | "archived") | null;
            /** Title */
            title?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** App Env */
            app_env: string;
            /**
             * Name
             * @default agent-platform
             */
            name: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /**
         * LongTermConfigDTO
         * @description `memory_config.long_term`：**MVP 不生效**（SD-15），字段保留以便迭代 A 不改数据。
         */
        LongTermConfigDTO: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Min Score
             * @default 0.35
             */
            min_score: number;
            /**
             * Retrieve Top K
             * @default 5
             */
            retrieve_top_k: number;
            /**
             * Scope
             * @default agent
             * @enum {string}
             */
            scope: "session" | "agent" | "user";
            /** Ttl Seconds */
            ttl_seconds?: number | null;
            /**
             * Write Policy
             * @default auto
             * @enum {string}
             */
            write_policy: "off" | "explicit" | "auto";
        };
        /** MemoryConfigDTO */
        MemoryConfigDTO: {
            long_term?: components["schemas"]["LongTermConfigDTO"];
            short_term?: components["schemas"]["ShortTermConfigDTO"];
        };
        /**
         * MessageCreate
         * @description `POST /conversations/{id}/messages` 的请求体（3.2.4）。
         *
         *     `stream` 默认 true（前端始终要流）；`model_overrides` 为本阶段的预留位（Phase 1 只接受空 dict）。
         */
        MessageCreate: {
            /** Content */
            content: string;
            /** Model Overrides */
            model_overrides?: {
                [key: string]: unknown;
            };
            /**
             * Stream
             * @default true
             */
            stream: boolean;
        };
        /** MessageRead */
        MessageRead: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Content
             * @default
             */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Model Name */
            model_name?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Role */
            role: string;
            /** Run Id */
            run_id?: string | null;
            /** Seq */
            seq: number;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** MetaData */
        MetaData: {
            /** App Env */
            app_env: string;
            features: components["schemas"]["MetaFeatures"];
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * MetaFeatures
         * @description 能力开关快照（6.3 第 5 条）。
         *
         *     `mcp` / `memory` / `eval_platform` 在 MVP **恒为 false**（SD-15/16/18：能力未实现）；
         *     前端据 `features` 隐藏对应菜单，无需改契约（3.2.1）。
         */
        MetaFeatures: {
            /**
             * Eval Platform
             * @default false
             */
            eval_platform: boolean;
            /**
             * File Write
             * @default false
             */
            file_write: boolean;
            /**
             * Mcp
             * @default false
             */
            mcp: boolean;
            /**
             * Memory
             * @default false
             */
            memory: boolean;
            /**
             * Python Execute
             * @default false
             */
            python_execute: boolean;
            /**
             * Web Search
             * @default false
             */
            web_search: boolean;
        };
        /**
         * ModelEntry
         * @description `models[]` 的一个白名单元素（2.3）。
         */
        ModelEntry: {
            /** Context Window */
            context_window?: number | null;
            /** Input Price Per 1K Usd */
            input_price_per_1k_usd?: number | null;
            /** Name */
            name: string;
            /** Output Price Per 1K Usd */
            output_price_per_1k_usd?: number | null;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /** Default Model */
            default_model?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** @default openai_compatible */
            kind: components["schemas"]["ProviderKind"];
            /** Models */
            models?: components["schemas"]["ModelEntry"][];
            /** Name */
            name: string;
            /**
             * Status
             * @default enabled
             * @enum {string}
             */
            status: "enabled" | "disabled";
        };
        /**
         * ProviderKind
         * @description LLM Provider 类型（4.1.2）。
         * @enum {string}
         */
        ProviderKind: "openai_compatible";
        /**
         * ProviderRead
         * @description 响应 DTO（**不含**任何明文密钥）。
         */
        ProviderRead: {
            /**
             * Api Key Masked
             * @default
             */
            api_key_masked: string;
            /** Base Url */
            base_url: string;
            /** Created At */
            created_at: string;
            /** Default Model */
            default_model?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /**
             * Has Api Key
             * @default false
             */
            has_api_key: boolean;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Kind */
            kind: string;
            /** Last Check At */
            last_check_at?: string | null;
            /** Last Check Error */
            last_check_error?: string | null;
            /** Models */
            models?: components["schemas"]["ModelEntry"][];
            /** Name */
            name: string;
            /**
             * Status
             * @default enabled
             */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ProviderTestResult
         * @description `POST /model-providers/{id}/test` 的结果（3.2.2：连通性检测，1-token）。
         */
        ProviderTestResult: {
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Provider Id */
            provider_id: string;
        };
        /**
         * ProviderUpdate
         * @description `PATCH`：只传需要改的字段；`api_key` 传空串表示清除。
         */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            } | null;
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Models */
            models?: components["schemas"]["ModelEntry"][] | null;
            /** Name */
            name?: string | null;
            /** Status */
            status?: ("enabled" | "disabled") | null;
        };
        /** ReadyzCheck */
        ReadyzCheck: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** ReadyzResponse */
        ReadyzResponse: {
            /** Checks */
            checks: components["schemas"]["ReadyzCheck"][];
            /** Status */
            status: string;
        };
        /**
         * ResponseMeta
         * @description `meta` 字段；`page*` / `total` 只在列表接口出现（3.1）。
         *
         *     `next_cursor` 是游标分页接口（`messages` / `traces`）的补充字段：
         *     为 `None` 表示没有更多数据；请求时把它原样回传 `?cursor=`（**不透明字符串**）。
         */
        ResponseMeta: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page */
            page?: number | null;
            /** Page Size */
            page_size?: number | null;
            /**
             * Request Id
             * @default
             */
            request_id: string;
            /** Total */
            total?: number | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * RunRead
         * @description `GET /runs/{run_id}`（3.2.4：含 steps / token / cost）。
         */
        RunRead: {
            /** Agent Id */
            agent_id?: string | null;
            /** Canceled At */
            canceled_at?: string | null;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Created At */
            created_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /** Kind */
            kind: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            };
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
            /**
             * Steps
             * @default 0
             */
            steps: number;
            /**
             * Tool Call Count
             * @default 0
             */
            tool_call_count: number;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * ShortTermConfigDTO
         * @description `memory_config.short_term`（2.4）。
         */
        ShortTermConfigDTO: {
            /**
             * Max Tokens
             * @default 6000
             */
            max_tokens: number;
            /**
             * Max Turns
             * @default 12
             */
            max_turns: number;
            /**
             * Strategy
             * @default window
             * @constant
             */
            strategy: "window";
            /**
             * Summarize Threshold Tokens
             * @default 4000
             */
            summarize_threshold_tokens: number;
        };
        /**
         * SpanRead
         * @description `GET /spans/{span_id}`：含完整 `input` / `output`（已按 4.8.2 截断）。
         */
        SpanRead: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Ended At */
            ended_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Run Id */
            run_id?: string | null;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /** Span Type */
            span_type: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @default running
             */
            status: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SpanSummary
         * @description Trace 详情里的扁平 span（不含 `input` / `output`）。
         */
        SpanSummary: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Ended At */
            ended_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /** Run Id */
            run_id?: string | null;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /** Span Type */
            span_type: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @default running
             */
            status: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * ToolDetail
         * @description 工具详情：附加 `api` 类型的 `http_config`（2.5）。
         */
        ToolDetail: {
            /** Builtin Name */
            builtin_name?: string | null;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Http Config */
            http_config?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Input Schema */
            input_schema?: {
                [key: string]: unknown;
            };
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
            /** Name */
            name: string;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            };
            /** Permission Config */
            permission_config?: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default enabled
             */
            status: string;
            /** Tags */
            tags?: string[];
            /**
             * Tool Type
             * @default builtin
             */
            tool_type: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ToolInvocationRead
         * @description `tool_invocations` 行（2.5）：每次调用的结构化明细（审计 / 前端工具卡片）。
         */
        ToolInvocationRead: {
            /** Approval Id */
            approval_id?: string | null;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /**
             * Call Index
             * @default 0
             */
            call_index: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Normalized Arguments */
            normalized_arguments?: {
                [key: string]: unknown;
            };
            /**
             * Permission Decision
             * @default allow
             */
            permission_decision: string;
            /** Result */
            result?: string | null;
            /**
             * Result Truncated
             * @default false
             */
            result_truncated: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Span Id
             * @default
             */
            span_id: string;
            /**
             * Status
             * @default succeeded
             */
            status: string;
            /**
             * Step Index
             * @default 0
             */
            step_index: number;
            /** Tool Id */
            tool_id?: string | null;
            /** Tool Name */
            tool_name: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
        };
        /**
         * ToolRead
         * @description `tools` 行（2.5，前端工具管理页与 Chat 工具卡片的展示字段）。
         */
        ToolRead: {
            /** Builtin Name */
            builtin_name?: string | null;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Id */
            id: string;
            /** Input Schema */
            input_schema?: {
                [key: string]: unknown;
            };
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
            /** Name */
            name: string;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            };
            /** Permission Config */
            permission_config?: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default enabled
             */
            status: string;
            /** Tags */
            tags?: string[];
            /**
             * Tool Type
             * @default builtin
             */
            tool_type: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * TraceDetail
         * @description `GET /traces/{trace_id}`：概要 + 扁平 span 列表（3.2.9）。
         */
        TraceDetail: {
            /** Spans */
            spans?: components["schemas"]["SpanSummary"][];
            trace: components["schemas"]["TraceRead"];
        };
        /** TraceRead */
        TraceRead: {
            /** Created At */
            created_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @default chat
             */
            kind: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Run Id */
            run_id?: string | null;
            /**
             * Span Count
             * @default 0
             */
            span_count: number;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @default running
             */
            status: string;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Workflow Run Id */
            workflow_run_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                q?: string | null;
                status_filter?: string | null;
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AgentRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AgentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AgentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AgentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_agent_api_v1_agents__agent_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCloneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AgentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_versions_api_v1_agents__agent_id__prompt_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AgentPromptVersionRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ConversationRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConversationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConversationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConversationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description 上一页返回的 meta.next_cursor */
                cursor?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_MessageRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description SSE 事件流（3.4） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MetaData_"];
                };
            };
        };
    };
    list_model_providers_api_v1_model_providers_get: {
        parameters: {
            query?: {
                q?: string | null;
                status_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ProviderRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_provider_api_v1_model_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProviderRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_provider_api_v1_model_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProviderRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_provider_api_v1_model_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_provider_api_v1_model_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProviderRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_provider_api_v1_model_providers__provider_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProviderTestResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                agent_id?: string | null;
                conversation_id?: string | null;
                status_filter?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_RunRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RunRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RunRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_span_api_v1_spans__span_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                span_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SpanRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tool_invocations_api_v1_tool_invocations_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                tool_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ToolInvocationRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: {
                /** @description `builtin` / `api` */
                tool_type?: string | null;
                /** @description `enabled` / `disabled` */
                status?: string | null;
                /** @description 按 name / display_name 模糊匹配 */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ToolRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_api_v1_tools__tool_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ToolDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_api_v1_traces_get: {
        parameters: {
            query?: {
                kind?: string | null;
                status_filter?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_TraceRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TraceDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description 依赖不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
}
