"""phase3 workflow tables（详细设计 7.4 / 2.9 / 4.5）

Revision ID: 0004_phase3_workflow_tables
Revises: 0003_phase2_tool_tables
Create Date: 2026-10-07

Phase 3 建 3 张表（7.4 交付物 / 2.9）：

    workflows · workflow_runs · node_runs

外加两处**已有表补 FK**（Phase 1 刻意"只建列不建 FK"，2.14 / 0002 的说明）：

- `agents.workflow_id` → `workflows.id`（`ON DELETE SET NULL`：删 Workflow 后 Agent 回落为
  "直接跑 AgentRuntime"，4.4.4）；
- `runs.workflow_run_id` → `workflow_runs.id`（同样 `SET NULL`：观测行不因清理 Workflow 而消失）。

两者都在 `batch_alter_table` 里显式命名（SQLite 重建表时无名约束无法再 drop），命名与
`app/db/models/agent.py` / `conversation.py` 的 `ForeignKey(..., name=...)` 保持一致，
这样 `alembic check` 在干净检出下报 `No new upgrade operations detected`。

`node_runs.seq` 是 3.2.7（"按 `seq` 排序"）要求的排序列，2.9 的表结构漏列，见附录 F v1.13。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004_phase3_workflow_tables"
down_revision: str | None = "0003_phase2_tool_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("state_schema", sa.JSON(), nullable=False),
        sa.Column("start_node_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("workflow_id", sa.String(length=26), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("definition_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("current_node_id", sa.String(length=64), nullable=True),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index("ix_workflow_runs_status", ["status"], unique=False)
        batch_op.create_index("ix_workflow_runs_trace_id", ["trace_id"], unique=False)
        batch_op.create_index("ix_workflow_runs_workflow_started", ["workflow_id", "started_at"], unique=False)

    op.create_table(
        "node_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("node_type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("agent_run_id", sa.String(length=26), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("node_runs", schema=None) as batch_op:
        batch_op.create_index("ix_node_runs_run_seq", ["run_id", "seq"], unique=False)

    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_agents_workflow_id_workflows", "workflows", ["workflow_id"], ["id"], ondelete="SET NULL"
        )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_runs_workflow_run_id_workflow_runs",
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_runs_workflow_run_id_workflow_runs", type_="foreignkey")

    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_agents_workflow_id_workflows", type_="foreignkey")

    with op.batch_alter_table("node_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_node_runs_run_seq")

    op.drop_table("node_runs")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_workflow_runs_workflow_started")
        batch_op.drop_index("ix_workflow_runs_trace_id")
        batch_op.drop_index("ix_workflow_runs_status")

    op.drop_table("workflow_runs")
    op.drop_table("workflows")
    # ### end Alembic commands ###
