"""phase5 knowledge tables（详细设计 7.6 / 2.8 / 4.6）

Revision ID: 0005_phase5_knowledge_tables
Revises: 0004_phase3_workflow_tables
Create Date: 2026-10-09

Phase 5 建 3 张表（7.6 交付物 / 2.8）：

    knowledge_bases · documents · chunks

**编号说明**：7.6 原文写的是 `0006_phase5_knowledge_tables`（当时假定 Phase 4 先行）。
实际实施**先做 Phase 5**（Phase 4 属 Backlog 迭代 A，SD-15），按"编号 = 实施顺序"取 `0005`，
Phase 4 的 `memory_items` 迁移相应顺延为 `0006`（附录 F v1.15）。

**索引说明**：2.8 明确要求 `chunks.kb_id` / `chunks.document_id` 建索引；`documents` 的两个复合索引
（`(kb_id, created_at)` 供列表页分页、`(kb_id, checksum)` 供 4.6.2 的幂等复用查询）是按接口契约补的，
同样记在附录 F v1.15。

命名规则（2.14）：`{revision}_phase{N}_{slug}`；每个 Phase 的迁移必须提供可用的 `downgrade()`。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005_phase5_knowledge_tables"
down_revision: str | None = "0004_phase3_workflow_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding_provider_id", sa.String(length=26), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("vector_store_kind", sa.String(length=16), nullable=False),
        sa.Column("collection_name", sa.String(length=64), nullable=False),
        sa.Column("splitter", sa.String(length=16), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("retriever_kind", sa.String(length=16), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("score_threshold", sa.Float(), nullable=False),
        sa.Column("rerank_enabled", sa.Boolean(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["embedding_provider_id"], ["model_providers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kb_id", sa.String(length=26), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["kb_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_documents_kb_checksum", ["kb_id", "checksum"], unique=False)
        batch_op.create_index("ix_documents_kb_created", ["kb_id", "created_at"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kb_id", sa.String(length=26), nullable=False),
        sa.Column("document_id", sa.String(length=26), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("vector_id", sa.String(length=26), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["kb_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_ordinal"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index("ix_chunks_document_id", ["document_id"], unique=False)
        batch_op.create_index("ix_chunks_kb_id", ["kb_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_kb_id")
        batch_op.drop_index("ix_chunks_document_id")

    op.drop_table("chunks")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_kb_created")
        batch_op.drop_index("ix_documents_kb_checksum")

    op.drop_table("documents")
    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###
